# .github/workflows/ci.yml
name: CI

#on:
#  pull_request:
#    branches:
#      - main  # Roda quando hรก PR para a branch main
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python (ou outra linguagem)
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest

      - name: Lint code
        run: |
          flake8 .
